FROM alpine:3.8

RUN apk add --update \
    bash \
    curl \
    rsync \
    libc6-compat \
    openssh \
    ca-certificates

WORKDIR /etc/maestro

COPY maestro /bin/maestro
COPY ./resources/default/ .

ENTRYPOINT ["/bin/maestro", "daemon"]