// Code generated by protoc-gen-go. DO NOT EDIT.
// source: annotations/annotations.proto

package annotations

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Service struct {
	Package              string   `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Protocol             string   `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Codec                string   `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_21dfaf6fd39fa3b7, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Service) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Service) GetCodec() string {
	if m != nil {
		return m.Codec
	}
	return ""
}

type HTTP struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTP) Reset()         { *m = HTTP{} }
func (m *HTTP) String() string { return proto.CompactTextString(m) }
func (*HTTP) ProtoMessage()    {}
func (*HTTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_21dfaf6fd39fa3b7, []int{1}
}

func (m *HTTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTP.Unmarshal(m, b)
}
func (m *HTTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTP.Marshal(b, m, deterministic)
}
func (m *HTTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTP.Merge(m, src)
}
func (m *HTTP) XXX_Size() int {
	return xxx_messageInfo_HTTP.Size(m)
}
func (m *HTTP) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTP.DiscardUnknown(m)
}

var xxx_messageInfo_HTTP proto.InternalMessageInfo

func (m *HTTP) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *HTTP) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

var E_Service = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*Service)(nil),
	Field:         50012,
	Name:          "maestro.service",
	Tag:           "bytes,50012,opt,name=service",
	Filename:      "annotations/annotations.proto",
}

var E_Http = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*HTTP)(nil),
	Field:         50011,
	Name:          "maestro.http",
	Tag:           "bytes,50011,opt,name=http",
	Filename:      "annotations/annotations.proto",
}

func init() {
	proto.RegisterType((*Service)(nil), "maestro.Service")
	proto.RegisterType((*HTTP)(nil), "maestro.HTTP")
	proto.RegisterExtension(E_Service)
	proto.RegisterExtension(E_Http)
}

func init() {
	proto.RegisterFile("annotations/annotations.proto", fileDescriptor_21dfaf6fd39fa3b7)
}

var fileDescriptor_21dfaf6fd39fa3b7 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0xfc, 0x30,
	0x10, 0xc5, 0xd9, 0xff, 0xbf, 0xbb, 0xd5, 0x88, 0x20, 0x41, 0x24, 0x2c, 0xa8, 0xcb, 0x22, 0xe2,
	0x29, 0x05, 0xbd, 0xf5, 0xa8, 0x17, 0x2f, 0x8b, 0x52, 0xf7, 0xe4, 0x2d, 0x4d, 0xc7, 0x36, 0xba,
	0xcd, 0x84, 0x76, 0x56, 0xbc, 0x78, 0xf5, 0x4b, 0xea, 0x87, 0x91, 0xa6, 0x69, 0x59, 0xf0, 0x36,
	0xef, 0x75, 0xf2, 0x9b, 0x79, 0x53, 0x76, 0xaa, 0xac, 0x45, 0x52, 0x64, 0xd0, 0xb6, 0xc9, 0x4e,
	0x2d, 0x5d, 0x83, 0x84, 0x3c, 0xae, 0x15, 0xb4, 0xd4, 0xe0, 0x7c, 0x51, 0x22, 0x96, 0x1b, 0x48,
	0xbc, 0x9d, 0x6f, 0x5f, 0x92, 0x02, 0x5a, 0xdd, 0x18, 0x47, 0xd8, 0xf4, 0xad, 0xcb, 0x4f, 0x16,
	0x3f, 0x41, 0xf3, 0x6e, 0x34, 0x70, 0xc1, 0x62, 0xa7, 0xf4, 0x9b, 0x2a, 0x41, 0x4c, 0x16, 0x93,
	0xab, 0xfd, 0x6c, 0x90, 0x9c, 0xb3, 0xc8, 0xaa, 0x1a, 0xc4, 0x3f, 0x6f, 0xfb, 0xba, 0xf3, 0x2a,
	0x6c, 0x49, 0xfc, 0xef, 0xbd, 0xae, 0xe6, 0x73, 0xb6, 0xe7, 0xa9, 0x1a, 0x37, 0x22, 0xf2, 0xfe,
	0xa8, 0xf9, 0x31, 0x9b, 0x6a, 0x2c, 0x40, 0x8b, 0xa9, 0xff, 0xd0, 0x8b, 0x65, 0xca, 0xa2, 0xfb,
	0xf5, 0xfa, 0xb1, 0x7b, 0x09, 0xb6, 0x70, 0x68, 0x2c, 0x85, 0xe1, 0xa3, 0xe6, 0x27, 0x6c, 0x56,
	0x03, 0x55, 0x58, 0x84, 0xf9, 0x41, 0xa5, 0x2b, 0x16, 0xb7, 0x61, 0xf5, 0x73, 0xd9, 0x07, 0x95,
	0x43, 0x50, 0x19, 0x42, 0x3d, 0x38, 0x7f, 0x17, 0xf1, 0xf3, 0xd5, 0xed, 0x79, 0x70, 0x7d, 0x24,
	0xc3, 0x69, 0x86, 0x86, 0x6c, 0x60, 0xa4, 0x77, 0x2c, 0xaa, 0x88, 0x1c, 0x3f, 0xfb, 0xc3, 0x5a,
	0xf9, 0x79, 0x03, 0xea, 0x3b, 0xa0, 0x0e, 0x47, 0x54, 0x97, 0x20, 0xf3, 0x8f, 0x6f, 0x2f, 0x9f,
	0x2f, 0x4a, 0x43, 0xd5, 0x36, 0x97, 0x1a, 0xeb, 0xe4, 0x15, 0x3e, 0x8c, 0x4a, 0x42, 0xdb, 0xee,
	0x7f, 0xca, 0x67, 0x1e, 0x7e, 0xf3, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x38, 0x16, 0xc4, 0xc4, 0xc9,
	0x01, 0x00, 0x00,
}
