// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/annotations.proto

package api // import "github.com/jexia/semaphore/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Service struct {
	Package              string   `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Transport            string   `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`
	Codec                string   `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_annotations_27c01f93e5594117, []int{0}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Service) GetTransport() string {
	if m != nil {
		return m.Transport
	}
	return ""
}

func (m *Service) GetCodec() string {
	if m != nil {
		return m.Codec
	}
	return ""
}

type HTTP struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTP) Reset()         { *m = HTTP{} }
func (m *HTTP) String() string { return proto.CompactTextString(m) }
func (*HTTP) ProtoMessage()    {}
func (*HTTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_annotations_27c01f93e5594117, []int{1}
}
func (m *HTTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTP.Unmarshal(m, b)
}
func (m *HTTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTP.Marshal(b, m, deterministic)
}
func (dst *HTTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTP.Merge(dst, src)
}
func (m *HTTP) XXX_Size() int {
	return xxx_messageInfo_HTTP.Size(m)
}
func (m *HTTP) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTP.DiscardUnknown(m)
}

var xxx_messageInfo_HTTP proto.InternalMessageInfo

func (m *HTTP) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *HTTP) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

var E_Service = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*Service)(nil),
	Field:         50012,
	Name:          "semaphore.api.service",
	Tag:           "bytes,50012,opt,name=service",
	Filename:      "api/annotations.proto",
}

var E_Http = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*HTTP)(nil),
	Field:         50011,
	Name:          "semaphore.api.http",
	Tag:           "bytes,50011,opt,name=http",
	Filename:      "api/annotations.proto",
}

func init() {
	proto.RegisterType((*Service)(nil), "semaphore.api.Service")
	proto.RegisterType((*HTTP)(nil), "semaphore.api.HTTP")
	proto.RegisterExtension(E_Service)
	proto.RegisterExtension(E_Http)
}

func init() { proto.RegisterFile("api/annotations.proto", fileDescriptor_annotations_27c01f93e5594117) }

var fileDescriptor_annotations_27c01f93e5594117 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x55, 0x48, 0x5b, 0xea, 0x4e, 0x58, 0x05, 0x59, 0x15, 0x82, 0xaa, 0x13, 0x93, 0x23,
	0xc1, 0x56, 0x36, 0x16, 0x58, 0x10, 0x50, 0x3a, 0xb1, 0x5d, 0x1d, 0x93, 0x18, 0x88, 0xcf, 0xb2,
	0xaf, 0x88, 0x8d, 0x8d, 0x2f, 0x09, 0x1f, 0x06, 0xc5, 0x71, 0xf8, 0x23, 0xb6, 0x7b, 0xef, 0x4e,
	0xbf, 0xbb, 0x77, 0x6c, 0x0f, 0x9c, 0xc9, 0xc1, 0x5a, 0x24, 0x20, 0x83, 0x36, 0x48, 0xe7, 0x91,
	0x90, 0x8f, 0x6b, 0xd0, 0x81, 0x3c, 0x4a, 0x70, 0x66, 0x3a, 0x2b, 0x11, 0xcb, 0x67, 0x9d, 0xc7,
	0xd6, 0x7a, 0xf3, 0x90, 0x17, 0x3a, 0x28, 0x6f, 0x1c, 0xa1, 0x6f, 0xc7, 0xe7, 0x6f, 0x6c, 0x78,
	0xa7, 0xfd, 0x8b, 0x51, 0x9a, 0x0b, 0x36, 0x74, 0xa0, 0x9e, 0xa0, 0xd4, 0xa2, 0x37, 0xeb, 0x1d,
	0x8f, 0x96, 0x9d, 0xe4, 0x9c, 0x65, 0x16, 0x6a, 0x2d, 0xb6, 0xa2, 0x1d, 0xeb, 0xc6, 0xab, 0x30,
	0x90, 0xd8, 0x6e, 0xbd, 0xa6, 0xe6, 0x07, 0x6c, 0x44, 0x1e, 0x6c, 0x70, 0xe8, 0x49, 0x64, 0xb1,
	0xf1, 0x63, 0xf0, 0x09, 0xeb, 0x2b, 0x2c, 0xb4, 0x12, 0xfd, 0xd8, 0x69, 0xc5, 0x7c, 0xc1, 0xb2,
	0xcb, 0xd5, 0xea, 0x86, 0x4f, 0xd9, 0x8e, 0xb6, 0x85, 0x43, 0x63, 0x29, 0xad, 0xff, 0xd6, 0x7c,
	0x9f, 0x0d, 0x6a, 0x4d, 0x15, 0x16, 0xe9, 0x82, 0xa4, 0x16, 0xb7, 0x6c, 0x18, 0xd2, 0xf1, 0x47,
	0xb2, 0x8d, 0x2a, 0xbb, 0xa8, 0x32, 0xc5, 0xba, 0x76, 0xf1, 0x3b, 0xe2, 0xf3, 0xbd, 0xb9, 0x74,
	0x7c, 0x32, 0x91, 0xbf, 0x1e, 0xd4, 0x0d, 0x2d, 0x3b, 0xce, 0xe2, 0x82, 0x65, 0x15, 0x91, 0xe3,
	0x87, 0xff, 0x78, 0x57, 0x71, 0x67, 0x87, 0xfb, 0x48, 0xb8, 0xdd, 0x3f, 0xb8, 0x26, 0xc9, 0x32,
	0x02, 0xce, 0xe7, 0xf7, 0xb3, 0xd2, 0x50, 0xb5, 0x59, 0x4b, 0x85, 0x75, 0xfe, 0xa8, 0x5f, 0x0d,
	0xe4, 0x69, 0x34, 0x07, 0x67, 0xce, 0xc0, 0x99, 0xf5, 0x20, 0xc2, 0x4f, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0xe5, 0xfa, 0xcf, 0xcb, 0x01, 0x00, 0x00,
}
